---
title: "PROYECTO"
author: " "
date: "MAYO 2025"
output:
  html_document:
    css: assets/rany_style.css
    df_print: paged
    highlight: tango
    theme: cosmo
    toc: yes
    toc_float:
      collapsed: true
    number_sections: true
---

<style>
body {
  text-align: justify;
}
</style>


```{r}
library(tseries)
library(dplyr)
library(lmtest)
library(forecast)
library(ggfortify)
```



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Generamos Tabla con los datos a evaluar
tabla<-read.csv('energia.csv')
tabla2<-select(tabla,Periodo=y,IE=x)
head(tabla2)

# Grafico de los datos
plot(tabla2$IE, type = 'l',
     main = "Índice de Generación, Transmisión y Distribución de Energía Eléctrica",
     col = "#3585A6",
     xlab = "Periodo mensual desde 2010",
     ylab = "Índice (base 2013 = 100)")


```


```{r}
# Prueba de Dickey Fuller Aumentada
x<-tabla2$IE
adf.test(x)
```
```{r}
# 1era Diferencia
d1x <- diff(x)
adf.test(d1x)  
plot(d1x, type = 'l',
     main = "Primera Diferencia de la Serie de Energía Eléctrica",
     col = "#2E628C",
     xlab = "Periodo",
     ylab = "Cambio mensual en el índice")

# Funcion de autocorrelacion (MA)
acf(d1x)

# Funcion de autocorrelacion parcial (AR)
pacf(d1x)

```

```{r}
# Ajustar un modelo Arima con AIC
p <- 3
q <- 3
d <- 0:2 

tabla0 <- data.frame()

for (d in d) {
  for (p in 0:p) {
    for (q in 0:q) {
      modelo <- tryCatch(
        arima(x, order = c(p, d, q)),
        error = function(e) NULL
      )
      if (!is.null(modelo)) {
        A <- AIC(modelo)
        tabla0 <- rbind(tabla0, c(p, d, q, A))
      }
    }
  }
}

colnames(tabla0) <- c("p", "d", "q", "AIC")
tabla0 <- arrange(tabla0, AIC) %>% head(5)
tabla0

```

```{r}
# Coeficientes significativos? Los 5 mejores 
# Calcular estadísticos t manualmente
modelo1 <- arima(x, order = c(3,1,3))
resumen <-summary(modelo1)
coeficientes <- coef(modelo1)
errores <- sqrt(diag(modelo1$var.coef))  # Errores estándar
t_calculado <- coeficientes / errores
significativos <- abs(t_calculado) >= 1.98
significativos


modelo2 <- arima(x, order = c(3,1,2))
resumen2<-summary(modelo1)
coeficientes <- coef(modelo2)
errores <- sqrt(diag(modelo2$var.coef))  # Errores estándar
t_calculado2 <- coeficientes / errores
significativos2 <- abs(t_calculado2) >= 1.98
significativos2


#modelo3 <- arima(x, order = c(3,1,1))
#summary(modelo1)

#modelo4 <- arima(x, order = c(2,0,2))
#summary(modelo1)

#modelo5 <- arima(x, order = c(3,0,3))
#summary(modelo1)
#coeficientes <- coeftest(modelo5)


```

```{r}
# Intervalos de confianza del mejor modelo
confint(modelo2, level = 0.95)

```
Ecuacion del mejor modelo

```{r}
modelo2 <- arima(x, order = c(3,1,2))
resumen2<-summary(modelo1)
resumen2
```

(1−1.1552R−0.0023R^2 +0.5776R^3)(1−R)^1*Xt=(1-1.4294R+0.4986R^2+0.2586R^3)Wt

```{r}
# Intervalos de confianza
coeficientes <- coef(modelo2)
errores <- sqrt(diag(modelo2$var.coef))


tabla_intervalos <- data.frame(
  Parametro = names(coeficientes),
  Estimacion = coeficientes,
  Std_Error = errores,
  LI = coeficientes - 1.98 * errores,  # Límite inferior
  LS = coeficientes + 1.98 * errores   # Límite superior
)

tabla_intervalos
```

```{r}
# Auto Arima
AA<-auto.arima(x)
AA

```

```{r}
# Intervalos de confianza
coeficientes <- coef(AA)
errores <- sqrt(diag(AA$var.coef))  # Errores estándar
t_calculado <- coeficientes / errores
significativos <- abs(t_calculado) >= 1.98
significativos
```
Ecuacion
(1-R)Xt= (1+0.1902R + 0.4488R^2)Wt


```{r}
# Intervalos de confianza
coeficientesA <- coef(AA)
erroresA <- sqrt(diag(AA$var.coef))


tabla_intervalosA <- data.frame(
  ParametroA = names(coeficientesA),
  EstimacionA = coeficientesA,
  Std_ErrorA = errores,
  LI = coeficientesA - 1.98 * erroresA,  # Límite inferior
  LS = coeficientesA + 1.98 * erroresA   # Límite superior
)

tabla_intervalosA
```

```{r}
n <- length(x)  # n = 160 (mayo 2023)
plot(forecast(AA, 50), xlim = c(n - 50, n + 50)) 
```













