---
title: "Tarea 2. Interpolación polinomial."
author: "Análisis Numérico."
date: "Febrero del 2024"
output: 
  prettydoc::html_pretty:
    toc: true
    theme: architect
header-includes:
   - \usepackage{amsmath}
---





<style>
body {
text-align: justify}
</style>



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyverse)
library(pracma)
library(plotly)
library(polynom)
```


**Definición.** Supongamos que $p^*$ es una aproximación de $p$. El **error real** es $p-p^*$, el **error absoluto** es $|p-p^*|$ y el error relativo es

\begin{equation}
\frac{|p-p^*|}{|p|},
\end{equation}

siempre y cuando $p\neq 0$.

# Ejercicio 1.

En cada inciso considera la función de valores reales, usa los polinomios interpolantes de Lagrange de grado a lo más tres con los puntos dados para aproximar el valor de la función solicitado.  En cada caso calcula el error real, el absoluto y el relativo.

a) $f(x)=e^{2x}$.  Puntos: $x_0=0, x_1=0.25, x_2=0.5, x_3=0.75$.  Aproximar $f(0.43)$.

b) $f(x)=x\,cos\,x-3x$.  Puntos: $x_0=0.1, x_1=0.2, x_2=0.3, x_3=0.4$.  Aproximar $f(0.18)$.

c) $f(x)=log(e^x+2)$.  Puntos: $x_0=-1, x_1=-0.5, x_2=0, x_3=0.5$.  Aproximar $f(0.25)$.

# Ejercicio 2

Se sospecha que las elevadas concentraciones de tanina en las hojas de los robles maduros inhiben el crecimiento de las larvas de la polilla invernal (*Operophtera bromata L. Geometridae*) que tanto dañan a los árboles en algunos años.  La tabla anexa contiene el peso promedio de dos muestras de larva, tomadas en los primeros 28 días después de nacimiento.  La primera muestra se crió en hojas de robles jóvenes, mientras que la segunda lo hizo en hojas maduras del mismo árbol.

a) Usa la interpolación polinomial para aproximar la curva del peso promedio de las muestras.

b) Para calcular un peso promedio máximo aproximado de cada muestra, determina el máximo del polinomio interpolante.

\begin{equation}
\begin{array}{l|c|c|c|c|c|c|r} 
\text{Día} & 0 & 6 & 10 & 13 & 17 & 20 & 28 \\
\hline \text{Peso promedio muestra 1 (mg)} & 6.67 & 17.33 & 42.67 & 37.33 & 30.10 & 29.31 & 28.74 \\
\text{Peso promedio muestra 2 (mg)} & 6.67 & 16.11 & 18.89 & 15.00 & 10.56 & 9.44 & 8.89
\end{array}
\end{equation}


# Ejercicio 3

Construye los polinomios interpolantes de grados $n=1,2,3,4$ para las siguientes funciones en el intervalo dado. 

a) $f(x) = e^{2x}\, cos 3x$, $[0,2]$. 

b) $f(x) = sen(log\,x)$, $[1,3]$.

c) $f(x) = e^{x}+e^{-x}$, $[0,2]$. 

d) $f(x) = cos \,x+sen\,x$, $[0,2\pi]$.






