---
title: "wage1_2"
output: html_document
date: "2024-08-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(dplyr)
```
```{r}
tabla1 <- read.csv("wage1.csv")
```
```{r}
modelo <- lm(educ ~ wage, tabla1)
coeficientes <-  coef(modelo)
b1 <- coeficientes[1]
b2 <- coeficientes[2]
b1
b2
```
```{r}
tabla2 <- select(tabla1, wage, educ)
tabla2 <- rename(tabla2, Y = wage, X = educ)
tabla2 <- mutate(tabla2, Xm2 = (X-mean(X))^2)
tabla2 <- mutate(tabla2, x = (mean(X))-X, x2=x^2)
tabla2 <- mutate(tabla2, y = (mean(Y))-Y)
tabla2 <- mutate(tabla2, y2 = y^2)
tabla2 <- mutate(tabla2, yi = (b1+(b2*X)))
tabla2 <- mutate(tabla2, yi2 = yi^2)
tabla2 <- mutate(tabla2, u = (Y-yi))
tabla2 <- mutate(tabla2, u2 = u^2)
head(tabla2)
```
```{r}
a10 <- b1+(10*b2)
a10
a16 <- b1+(16*b2)
a16
a1 <- b1+(1*b2)
a1
a4 <- b1+(4*b2)
a4
```

```{r}
y2 <- sum(tabla2$y2)
y2
yi2 <- sum(tabla2$yi2)
yi2
u2 <- sum(tabla2$u2)
u2
```
```{r}
plot(u~X, data = tabla2)
```

```{r}
vari <- (sum(tabla2$u2))/(n-2)
vari
varb2 <- vari/sum(tabla2$x2)
varb2
eeb2 <- sqrt(vari)/sqrt(sum(tabla2$x2))
eeb2
varb1 <- (sum(tabla2$x2)/(n*sum(tabla2$x2)))*vari
varb1
eeb1 <- sqrt((sum(tabla2$x2)/(n*sum(tabla2$x2))))*sqrt(vari)
eeb1
cova <- -mean(tabla2$X)*varb2
cova
```
```{r}
summary(modelo)
```




