
---
title: "Practica 4  "
author: " Murillo Alba Josué Iván"
date: "Marzo 2025"
output: 
  html_document:
    toc: true
    toc_depth: 1
    theme: journal
---


<style>
body {
text-align: justify}
</style>

```{r}
library(tseries)




n <- 500
w <- rnorm(n)
x <- numeric(n)

for(t in 2:n)
  x[t] <- x[t-1] + w[t]
plot(x, type = 'l')

acf(x)

adf.test(x)

d1x <- diff(x)
adf.test(d1x)

plot(d1x, type = 'l')





n = 600
w <- rnorm(n)
x <- numeric(n)
dx <- numeric(n)

for (t in 2:n) {
  x[t] <- x[t-1] + w[t]
  
}

plot(x, type = 'l')

d1x <- diff(x)

for(t in 2:n)
  dx[t] <- x[t] - x[t-1]
    
dx <- dx[-c(1)]

head(dx)
head(d1x)


plot(d1x, type = 'l')


acf(d1x)



```





```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tseries)
```







# Series de Tiempo Integradas {.tabset}

## a)
Carga en R los datos del archivo. Los datos contienen una serie de tiempo.
```{r}
file1 <- read.csv('PracR.csv')
file2<- read.csv('PracT.csv')
file3<- read.csv('PracX.csv')
file4<- read.csv('PracY.csv')
```


## b)
Determina si la serie de tiempo es estacionaria o no. Realiza la gr´afica y
utiliza la prueba de Dickey-Fuller Aumentada.
Explica por que es o por qu´e no es estacionaria.

```{r}
x <- file1$x
n <- nrow(file1)

# Original
plot(x, type = 'l', main = "Serie Original", col = "cyan", xlab = "Tiempo", ylab = "Valor")

acf(x, main = "ACF de la Serie Original")

# Prueba DF
adf_result <- adf.test(x)
print(adf_result)

# Diferenciar
d1x <- diff(x)
adf.test(d1x)  

plot(d1x, type = 'l')
acf(d1x)

# Diferencia 2
d2x <- diff(d1x)
adf.test(d2x)  

plot(d2x, type = 'l')
acf(d2x)



```
Reglas








